apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtf
  namespace: nju29
  labels:
    app: rtf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtf
  template:
    metadata:
      labels:
        app: rtf
    spec:
      containers:
        - name: rtf
          image: harbor.edu.cn/nju29/python:latest
          command: ["/bin/sh"]
          args: ["-c", 'curl "http://p2.nju.edu.cn/portal_io/login" --data "username=181250090&password=willy229liu" && curl https://git.nju.edu.cn/211250026/sh/-/raw/main/rtf.robot -o /tmp/rtf.robot && pip install requests && pip install robotframework && cat /tmp/rtf.robot && curl 172.29.4.34:31960/greeting && robot /tmp/rtf.robot']
      imagePullSecrets:
        - name: nju29
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rtf
  name: rtf
  namespace: nju29
spec:
#  containers:
#    - command:
#        - --service-node-port-range=30000-32000
#        - --service-node-port-range=38000-39000
#        - --service-node-port-range=40000-41000
  ports:
    - name: tcp
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31806
  selector:
    app: rtf
  type: NodePort