apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtf
  namespace: nju29
  labels:
    app: rtf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtf
  template:
    metadata:
      labels:
        app: rtf
    spec:
      containers:
        - name: rtf
          image: python
          command: ["/bin/sh"]
          args: ["-c", 'pip install requests && pip install robotframework && robot ./jenkins/scripts/rtf.robot']
      imagePullSecrets:
        - name: nju29
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rtf
  name: rtf
  namespace: nju29
spec:
#  containers:
#    - command:
#        - --service-node-port-range=30000-32000
#        - --service-node-port-range=38000-39000
#        - --service-node-port-range=40000-41000
  ports:
    - name: tcp
      port: 80
      protocol: TCP
      targetPort: 80
#      nodePort: 40001
  selector:
    app: rtf
  type: NodePort